project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://luatil.github.io/
  title: "blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/luatil
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



